### ISSUE TITLE
If element has no image background

### ISSUE THREAD

**Issue by digikokki** [xinyu198736/sketch-to-html#8]
The build process will crash if there is no image background on a layer.
So if you make a new sketch file that have just one page and one artboard and make Rectangle without background image the npm run example will give fs.js:961
  binding.lstat(pathModule.toNamespacedPath(path));

**Comment by digikokki** [comment]
index.js:47:13)
    at ChildProcess.exithandler (child_process.js:264:7)
    at ChildProcess.emit (events.js:159:13)
    at maybeClose (internal/child_process.js:943:16)
    at Socket.stream.socket.on (internal/child_process.js:363:11)
